In [1]:
def get_data(n_timepoints=100, n_channels=10):
    import numpy as np
    import pandas as pd
    return pd.DataFrame(np.random.rand(n_timepoints, n_channels))

def get_paradigm(n_timepoints=100):
    # All between 0 and 180 degrees in radians
    import numpy as np
    import pandas as pd
    return pd.DataFrame(np.random.rand(n_timepoints) * np.pi)

In [4]:
from braincoder.stimuli import OneDimensionalRadialStimulus

In [18]:
from braincoder.models import GaussianPRF, VonMisesPRF
from braincoder.optimize import ParameterFitter
import numpy as np

data = get_data() # Neural data n_timepoints x n_channels
paradigm = get_paradigm() # Orientations
model = VonMisesPRF(paradigm=paradigm, data=data)

mus = np.linspace(0, np.pi, 8)
sds = np.array([0.1, 0.5, 1.0])
amplitudes = [1.0]
baselines = [0.0]

fitter = ParameterFitter(model=model, data=data, paradigm=paradigm)

# Do a quick grid search first
grid_pars = fitter.fit_grid(mus, sds, amplitudes, baselines, use_correlation_cost=True)

# Optimize amplitude and baseline using OLS
grid_pars = fitter.refine_baseline_and_amplitude(grid_pars)

# Use gradient descent to further refine mu and sd
gd_pars = fitter.fit(init_pars=grid_pars)
r2 = fitter.get_rsq(gd_pars)

<braincoder.stimuli.OneDimensionalRadialStimulus object at 0x31120c0d0>
Working with chunk size of 666666
Using correlation cost!

100%|██████████| 1/1 [00:00<00:00, 19.55it/s]

*** Fitting: ***
 * mu
 * kappa
 * amplitude
 * baseline
Number of problematic voxels (mask): 0
Number of voxels remaining (mask): 10

Current R2: 0.03197/Best R2: 0.03197: 100%|██████████| 1000/1000 [00:05<00:00, 171.74it/s]

In [19]:
r2

source
0    0.016479
1    0.078712
2    0.049225
3    0.052280
4    0.011282
5    0.039234
6    0.022591
7    0.006330
8    0.032624
9    0.010977
Name: r2, dtype: float32

In [ ]:
jfitter.fit_grid?

Signature:
fitter.fit_grid(
    *args,
    fixed_pars=None,
    use_correlation_cost=False,
    positive_amplitude=True,
    **kwargs,
)
Docstring: <no docstring>
File:      ~/git/braincoder/braincoder/optimize.py
Type:      method

,0,1,2,3,4,5,6,7,8,9
0,0.271948,0.371245,0.042285,0.279944,0.730767,0.742494,0.630002,0.871496,0.627059,0.442555
1,0.932515,0.390854,0.158880,0.142530,0.420049,0.626299,0.520952,0.233747,0.375717,0.132978
2,0.023157,0.774109,0.275024,0.569347,0.887094,0.949581,0.378182,0.415033,0.939373,0.821894
3,0.096043,0.025018,0.048944,0.465398,0.558542,0.454393,0.552771,0.585745,0.752378,0.647702
4,0.820390,0.586199,0.224184,0.223530,0.741223,0.519561,0.115622,0.429659,0.284802,0.721415
...,...,...,...,...,...,...,...,...,...,...
95,0.171068,0.599978,0.672913,0.372273,0.394051,0.467861,0.316812,0.139984,0.174216,0.018542
96,0.763192,0.655804,0.474476,0.085358,0.592534,0.325785,0.017553,0.766837,0.620502,0.528378
97,0.960726,0.454234,0.156748,0.842039,0.196991,0.260574,0.063567,0.025770,0.179083,0.715383
98,0.013412,0.380718,0.272917,0.624981,0.404437,0.279183,0.584651,0.390059,0.006709,0.071943
99,0.917875,0.311579,0.178858,0.698183,0.526510,0.372047,0.801778,0.569930,0.840541,0.898044

In [ ]:
from braincoder.models import GaussianPRF, VonMisesPRF
from braincoder.optimize import ParameterFitter
data = get_data() # Neural data n_timepoints x n_channels
paradigm = get_paradigm() # Orientations
model = VonMisesPRF(paradigm=paradigm, data=data)
fitter = ParameterFitter(model=model, data=data, paradigm=paradigm)

fitter.fit()

           0
0   0.976944
1   1.587566
2   2.051803
3   0.844932
4   2.534133
..       ...
95  2.418682
96  1.060070
97  0.226069
98  0.412622
99  0.473639

[100 rows x 1 columns]